#include "archsynth/search/mutations.h"
#include <algorithm>
namespace archsynth { namespace { bool valid(const Genotype& g){ std::string e; return g.to_graph().is_valid(e); } std::string fresh_id(const Genotype& g){ int i=0; for(;;++i){ auto id="n"+std::to_string(i); if(std::none_of(g.nodes.begin(),g.nodes.end(),[&](auto&n){return n.id==id;})) return id; } } }
bool AddNodeMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ auto names=list_primitives(); names.erase(std::remove_if(names.begin(),names.end(),[](const std::string& name){return primitive_input_kind(name)!=TensorKind::FloatFeatures||primitive_min_inputs(name)!=1;}),names.end()); std::vector<size_t> edges; for(size_t i=0;i<g.edges.size();++i) if(g.edges[i].first!="input") edges.push_back(i); if(names.empty()||edges.empty()) return false; std::uniform_int_distribution<size_t> primitive(0,names.size()-1), edge_index(0,edges.size()-1); std::string id=fresh_id(g); g.nodes.push_back({id,names[primitive(rng)],{}}); const size_t selected=edges[edge_index(rng)]; auto edge=g.edges[selected]; g.edges.erase(g.edges.begin()+static_cast<std::ptrdiff_t>(selected)); g.edges.push_back({edge.first,id}); g.edges.push_back({id,edge.second}); return valid(g); }
bool RemoveNodeMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ if(g.nodes.size()<2) return false; std::uniform_int_distribution<size_t>d(0,g.nodes.size()-1); auto id=g.nodes[d(rng)].id; std::vector<std::string> srcs,dsts; for(auto&e:g.edges){ if(e.second==id) srcs.push_back(e.first); if(e.first==id) dsts.push_back(e.second); } g.nodes.erase(std::remove_if(g.nodes.begin(),g.nodes.end(),[&](auto&n){return n.id==id;}),g.nodes.end()); g.edges.erase(std::remove_if(g.edges.begin(),g.edges.end(),[&](auto&e){return e.first==id||e.second==id;}),g.edges.end()); for(auto&s:srcs) for(auto&d:dsts) g.edges.push_back({s,d}); return valid(g); }
bool ChangePrimitiveMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ if(g.nodes.empty()) return false; auto names=list_primitives(); std::uniform_int_distribution<size_t> nd(0,g.nodes.size()-1), pd(0,names.size()-1); auto& n=g.nodes[nd(rng)]; n.primitive_name=names[pd(rng)]; n.hyperparams=default_hyperparams_for(n.primitive_name); return valid(g); }
bool ChangeHyperparamMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ if(g.nodes.empty()) return false; std::uniform_int_distribution<size_t>d(0,g.nodes.size()-1); auto& hp=g.nodes[d(rng)].hyperparams; if(hp.empty()) return false; auto it=hp.begin(); std::advance(it, std::uniform_int_distribution<size_t>(0,hp.size()-1)(rng)); it->second=std::max(1.0,it->second*(std::uniform_real_distribution<double>(0.5,1.5)(rng))); return valid(g); }
bool AddEdgeMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ auto old=g; std::vector<std::string> ids={"input","output"}; for(auto&n:g.nodes) ids.push_back(n.id); std::uniform_int_distribution<size_t>d(0,ids.size()-1); for(int tries=0;tries<20;++tries){ auto s=ids[d(rng)], t=ids[d(rng)]; if(s==t||s=="output"||t=="input") continue; g.edges.push_back({s,t}); if(valid(g)) return true; g=old; } return false; }
bool RemoveEdgeMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector&){ if(g.edges.size()<2) return false; std::uniform_int_distribution<size_t>d(0,g.edges.size()-1); g.edges.erase(g.edges.begin()+d(rng)); return valid(g); }
void CompositeMutation::add_mutation(std::unique_ptr<Mutation> m,double w){ muts_.push_back(std::move(m)); weights_.push_back(w); }
bool CompositeMutation::apply(Genotype& g,std::mt19937& rng,const ConditionVector& c){ if(muts_.empty()) return false; const auto original=g; std::discrete_distribution<size_t>d(weights_.begin(),weights_.end()); if(!muts_[d(rng)]->apply(g,rng,c)||!valid(g)){ g=original; return false; } return true; }
std::unique_ptr<CompositeMutation> create_default_mutations(){ auto c=std::make_unique<CompositeMutation>(); c->add_mutation(std::make_unique<AddNodeMutation>(),2); c->add_mutation(std::make_unique<RemoveNodeMutation>(),1); c->add_mutation(std::make_unique<ChangePrimitiveMutation>(),2); c->add_mutation(std::make_unique<ChangeHyperparamMutation>(),2); c->add_mutation(std::make_unique<AddEdgeMutation>(),1); c->add_mutation(std::make_unique<RemoveEdgeMutation>(),1); return c; }
}
